version: '3.8'
services:
  api:
    container_name: nest_app
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      .env
    ports:
      - 3000:3000
    networks:
      - nestjscurd
  db:
    container_name: nest_mongo
    image: mongo:4.4
    ports:
      - 5001:27017
    env_file:
      .env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db
    networks:
      - nestjscurd
networks:
  nestjscurd: